server:
  port: 9999

spring:
  rabbitmq:
    host: 123.206.50.50
    username: root
    password: kshop
  # zipkin:
  #     base-url: http://localhost:5002
  # sleuth:
  #   enabled: true
  #   sampler:
  #     perce  ntage: 1
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth-service:
      path: /auth/**
      serviceId: greatPay-auth
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie
    greatPay-admin-service:
      path: /admin/**
      serviceId: greatPay-upms-service
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie
  ratelimit:
    key-prefix: greatPay-ratelimite 
    enabled: true 
    repository: REDIS 
    behind-proxy: true
    policies:
      greatPay-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3
    

filter:
  urls:
    anon:
      - /auth/**
      - /admin/code/*
      - /swagger-resources/**
      - /swagger-ui.html
      - /*/v2/api-docs
      - /swagger/api-docs
      - /webjars/**
       
logging:
  config: classpath:logback.xml