server:
  port: 4050
spring:
  datasource:   
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.50.50:3306/greatPay?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test
    initialize: false
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.ch.greatPay.*.entity
#  global-config:
#    id-type: 3
#    field-strategy: 2
#    auto-set-db-type: true
#    db-column-underline: true
#    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false        

druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10
#qiniu:
##  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
#  bucket: pigcloud
 # host: http://p0hpm86wj.bkt.clouddn.com/
#fdfs:
#  file-host: 123.206.50.50    
fdfs: 
  file-host: 123.206.50.50:22122
  